# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-134230067-3'

menu:
- {name: 'Cities',  url: ''}
- {name: 'About', url: 'about'}

related_posts: 'Next up…'