# config.yml

backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads/images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero image', name: 'image', widget: 'image', allow_multiple: false, media_folder: '/assets/uploads/images' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  
  - name: 'page'
    label: 'Page'
    folder: 'pages'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - label: 'Settings'
        name: 'settings'
        file: '_data/settings.yml'
        fields:
          - label: '"Related Posts" text'
            name: 'related_posts'
            widget: 'string'

          - label: 'Google Analytics ID'
            name: 'google-ID'
            widget: 'string'

          - label: 'Menu items'
            name: 'menu'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: URL, name: url, widget: string }